name: Maven Test with Allure Report

on:
  schedule:
    # Runs the workflow every hour
    - cron: '0 * * * *'
  workflow_dispatch: # For manually triggering the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up JDK (Java 22)
    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '22'

    # Cache Maven dependencies to avoid redownloading packages every test run
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Install Maven dependencies and run tests
    - name: Run Maven tests
      run: mvn clean test

    # Upload Allure results
    - name: Upload Allure Results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: target/allure-results

    # Generate Allure Report using Allure CLI
    - name: Generate Allure Report
      run: |
        allure generate target/allure-results --clean -o allure-report

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
